import type { Metadata, Viewport } from "next";
import "@/styles/globals.css";
import { satoshi } from "@/styles/fonts";
import TopBanner from "@/components/layout/Banner/TopBanner";
import TopNavbar from "@/components/layout/Navbar/TopNavbar";
import Footer from "@/components/layout/Footer";
import HolyLoader from "holy-loader";

export const metadata: Metadata = {
  title: "Shopper",
  description: "Generated by create next app",
};



export default function FrontendLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <HolyLoader color="#868686" />
      <TopBanner />
      <TopNavbar />
      {children}
      <Footer />
    </>
  );
}
